# Access via "http://localhost:8888"
# phpmyadmin Access via "http://localhost:8889"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: drupal-persist
    restart: always
    environment:
      MYSQL_DATABASE: drupal 
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupal-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass 
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8889:80
  drupal:
    image: drupal:9-apache-buster 
    container_name: drupal-www
    ports:
      - 8888:80
    restart: always
    volumes:
      - .:/opt:z
    working_dir: /opt
    command: bash -c "composer update && rm /var/www/html && ln -s /opt/web /var/www/html && /usr/local/bin/apache2-foreground"
