version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: drupal-persist
    restart: always
    environment:
      MYSQL_DATABASE: ${DB} 
      MYSQL_USER: ${DBU} 
      MYSQL_PASSWORD: ${DBP} 
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupal-phpmyadmin
    environment:
      PMA_HOST: ${DBH}
      PMA_USER: ${DBU} 
      PMA_PASSWORD: ${DBP} 
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8889:80
  drupal:
    image: drupal:9-apache-buster 
    container_name: drupal-www
    ports:
      - 8888:80
    restart: always
    volumes:
      - .:/opt:z
    working_dir: /opt
    command: bash -c "composer update && rm /var/www/html && ln -s /opt/web /var/www/html && chmod -R 777 /opt/web/sites/default/files && /usr/local/bin/apache2-foreground"
